# Generated by Django 4.0.5 on 2022-07-13 09:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(upload_to='avatar/%y/%m')),
                ('diachi', models.TextField()),
                ('ngaysinh', models.DateField(null=True)),
                ('sodienthoai', models.CharField(max_length=12)),
                ('quyenquanlyduan', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateField(auto_created=True)),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('ngaybatdau', models.DateTimeField(blank=True, default=None, null=True)),
                ('ngayketthuc', models.DateTimeField(blank=True, default=None, null=True)),
                ('ngaybatdauthucte', models.DateField(blank=True, default=None, null=True)),
                ('ngayketthucthute', models.DateField(blank=True, default=None, null=True)),
                ('idnhanvienthamgia', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbophan', models.CharField(max_length=100, unique=True)),
                ('tenphongban', models.CharField(max_length=100, unique=True)),
                ('ngaytao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('mota', models.TextField()),
                ('createby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpdata.itembase')),
                ('chiphi', models.IntegerField()),
                ('trangthai', models.BooleanField(default=False)),
                ('mota', models.TextField()),
            ],
            bases=('erpdata.itembase',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpdata.itembase')),
                ('loaiduan', models.CharField(max_length=100)),
                ('trangthai', models.IntegerField(default=1)),
                ('duanquantrong', models.BooleanField()),
                ('maduan', models.CharField(max_length=100)),
                ('idbophanthamgiaduan', models.ManyToManyField(blank=True, null=True, to='erpdata.part')),
            ],
            bases=('erpdata.itembase',),
        ),
        migrations.CreateModel(
            name='SampleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mota', models.TextField()),
                ('trangthai', models.BooleanField(default=False)),
                ('createby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nguoiduyet', models.ManyToManyField(blank=True, related_name='nguuoiduyetbm', to=settings.AUTH_USER_MODEL)),
                ('nguoinhanthongbao', models.ManyToManyField(blank=True, related_name='nguoinhanthongbaobm', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.process')),
            ],
        ),
        migrations.CreateModel(
            name='SampleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_created=True)),
                ('ten', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.process')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255, unique=True)),
                ('mausac', models.CharField(max_length=255, unique=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='part',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erpdata.part'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('itembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpdata.itembase')),
                ('mota', models.TextField()),
                ('trangthai', models.BooleanField(default=False)),
                ('chiphi', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.categorys')),
                ('process', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='erpdata.process')),
            ],
            bases=('erpdata.itembase',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_created=True)),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('vitri', models.CharField(max_length=100, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('mota', models.TextField()),
                ('trangthai', models.BooleanField()),
                ('createby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nguoiduyet', models.ManyToManyField(blank=True, related_name='nguuoiduyetcvbs', to=settings.AUTH_USER_MODEL)),
                ('nguoinhanthongbao', models.ManyToManyField(blank=True, related_name='nguoinhanthongbaocvbs', to=settings.AUTH_USER_MODEL)),
                ('Work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.work')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_created=True)),
                ('ten', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.work')),
            ],
        ),
        migrations.CreateModel(
            name='CostOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_created=True)),
                ('chiphi', models.IntegerField()),
                ('songaycongtac', models.IntegerField()),
                ('tiencongtac', models.IntegerField()),
                ('tienkm', models.IntegerField()),
                ('sokmdadi', models.IntegerField()),
                ('thanhtien', models.IntegerField()),
                ('ngaybatdau', models.DateTimeField(null=True)),
                ('ngayketthuc', models.DateTimeField(null=True)),
                ('bophanthamgia', models.ManyToManyField(blank=True, null=True, related_name='bophanthamgiacongtac', to='erpdata.part')),
                ('nhanvienthamgia', models.ManyToManyField(blank=True, related_name='nhanvienthamgiacongtac', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_created=True)),
                ('noidung', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.categorys')),
            ],
        ),
        migrations.AddField(
            model_name='categorys',
            name='role',
            field=models.ManyToManyField(null=True, to='erpdata.role'),
        ),
        migrations.AddField(
            model_name='categorys',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpdata.stage'),
        ),
    ]
